import mongoose from "mongoose";
import bcrypt from "bcryptjs";

const MONGODB_URI = process.env.MONGODB_URI || "mongodb://127.0.0.1:27017/hospital_management";

async function seed() {
  console.log("Connecting to MongoDB at:", MONGODB_URI);
  await mongoose.connect(MONGODB_URI);
  console.log("Connected successfully. Clearing old collections...");

  const db = mongoose.connection.db;
  const collections = await db.listCollections().toArray();
  for (const col of collections) {
    try {
      await db.collection(col.name).drop();
    } catch (e) {
      console.log(`Could not drop ${col.name}`);
    }
  }

  console.log("Creating default hospital setting...");
  await db.collection("hospitalsettings").insertOne({
    hospitalName: "MediPulse Hospital & Medical Institute",
    tagline: "World-Class Compassionate Healthcare, AI Diagnostics & ABDM Integrated",
    email: "info@medipulsehospital.com",
    phone: "+91 1800-456-7890",
    emergencyHotline: "+91 1800-911-0000",
    address: "Plot 42, Health City, Sector 62",
    city: "New Delhi",
    state: "Delhi NCR",
    zipCode: "110001",
    taxId: "GSTIN-07AABCM9821Q1Z8",
    currencySymbol: "₹",
    timezone: "Asia/Kolkata",
    createdAt: new Date(),
    updatedAt: new Date(),
  });

  console.log("Creating users for all roles...");
  const hashedPassword = await bcrypt.hash("password123", 10);
  const users = [
    {
      name: "Dr. Alexander Wright",
      email: "admin@hospital.com",
      password: hashedPassword,
      role: "SUPER_ADMIN",
      employeeId: "STF-ADMIN-01",
      phone: "+91 9876543210",
      department: "Administration",
      status: "active",
      avatar: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80",
      mciRegistrationNumber: "MCI-ADMIN-001",
      qualification: "MD, MHA, FRCS",
      bio: "Medical Superintendent with 18+ years of clinical governance and healthcare informatics leadership.",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Dr. Sarah Jenkins",
      email: "doctor@hospital.com",
      password: hashedPassword,
      role: "DOCTOR",
      employeeId: "DOC-2026-001",
      phone: "+91 9876543211",
      department: "Cardiology",
      status: "active",
      avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80",
      mciRegistrationNumber: "MCI-CARD-9921",
      qualification: "MBBS, MD (Medicine), DM (Cardiology)",
      bio: "Senior Interventional Cardiologist specializing in complex coronary interventions and preventive cardiology.",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Emma Davis",
      email: "receptionist@hospital.com",
      password: hashedPassword,
      role: "RECEPTIONIST",
      employeeId: "STF-102",
      phone: "+91 9876543212",
      department: "Front Desk",
      status: "active",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
      qualification: "BBA Healthcare Management",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Nurse Clara Oswald",
      email: "nurse@hospital.com",
      password: hashedPassword,
      role: "NURSE",
      employeeId: "STF-103",
      phone: "+91 9876543213",
      department: "Inpatient Ward",
      status: "active",
      avatar: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=150&auto=format&fit=crop&q=80",
      qualification: "B.Sc Nursing, Critical Care Certified",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Marcus Vance",
      email: "pharmacist@hospital.com",
      password: hashedPassword,
      role: "PHARMACIST",
      employeeId: "STF-104",
      phone: "+91 9876543214",
      department: "Pharmacy",
      status: "active",
      avatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80",
      qualification: "B.Pharm, M.Pharm (Clinical)",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "David Chen",
      email: "lab@hospital.com",
      password: hashedPassword,
      role: "LAB_TECHNICIAN",
      employeeId: "STF-105",
      phone: "+91 9876543215",
      department: "Laboratory",
      status: "active",
      avatar: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80",
      qualification: "B.Sc Medical Laboratory Technology (BMLT)",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Arthur Pendelton",
      email: "billing@hospital.com",
      password: hashedPassword,
      role: "ACCOUNTANT",
      employeeId: "STF-106",
      phone: "+91 9876543216",
      department: "Finance & Accounts",
      status: "active",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
      qualification: "Chartered Accountant (CA), B.Com",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Elena Rostova",
      email: "radiology@hospital.com",
      password: hashedPassword,
      role: "RADIOLOGY_TECHNICIAN",
      employeeId: "STF-107",
      phone: "+91 9876543218",
      department: "Radiology & Imaging",
      status: "active",
      avatar: "https://images.unsplash.com/photo-1594824813580-b2b93e506941?w=150&auto=format&fit=crop&q=80",
      qualification: "B.Sc Radiography & Medical Imaging Technology",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "John Miller",
      email: "patient@hospital.com",
      password: hashedPassword,
      role: "PATIENT",
      patientId: "PAT-8001",
      phone: "+91 9876543217",
      status: "active",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
  await db.collection("users").insertMany(users);

  console.log("Creating Staff records...");
  const staffMembers = [
    {
      staffId: "STF-ADMIN-01",
      name: "Dr. Alexander Wright",
      email: "admin@hospital.com",
      phone: "+91 9876543210",
      role: "SUPER_ADMIN",
      department: "Administration",
      designation: "Medical Superintendent",
      joiningDate: "2018-01-15",
      salary: 220000,
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      staffId: "DOC-2026-001",
      name: "Dr. Sarah Jenkins",
      email: "doctor@hospital.com",
      phone: "+91 9876543211",
      role: "DOCTOR",
      department: "Cardiology",
      designation: "Senior Interventional Cardiologist",
      joiningDate: "2019-03-01",
      salary: 180000,
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      staffId: "STF-102",
      name: "Emma Davis",
      email: "receptionist@hospital.com",
      phone: "+91 9876543212",
      role: "RECEPTIONIST",
      department: "Front Desk",
      designation: "Front Desk Officer",
      joiningDate: "2021-06-15",
      salary: 45000,
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      staffId: "STF-103",
      name: "Nurse Clara Oswald",
      email: "nurse@hospital.com",
      phone: "+91 9876543213",
      role: "NURSE",
      department: "Inpatient Ward",
      designation: "Lead Ward Nurse",
      joiningDate: "2020-09-10",
      salary: 65000,
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      staffId: "STF-104",
      name: "Marcus Vance",
      email: "pharmacist@hospital.com",
      phone: "+91 9876543214",
      role: "PHARMACIST",
      department: "Pharmacy",
      designation: "Chief Pharmacist",
      joiningDate: "2019-11-20",
      salary: 75000,
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      staffId: "STF-105",
      name: "David Chen",
      email: "lab@hospital.com",
      phone: "+91 9876543215",
      role: "LAB_TECHNICIAN",
      department: "Laboratory",
      designation: "Senior Lab Technologist",
      joiningDate: "2021-02-14",
      salary: 58000,
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      staffId: "STF-106",
      name: "Arthur Pendelton",
      email: "billing@hospital.com",
      phone: "+91 9876543216",
      role: "ACCOUNTANT",
      department: "Finance & Accounts",
      designation: "Finance Manager",
      joiningDate: "2018-08-01",
      salary: 85000,
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      staffId: "STF-107",
      name: "Elena Rostova",
      email: "radiology@hospital.com",
      phone: "+91 9876543218",
      role: "RADIOLOGY_TECHNICIAN",
      department: "Radiology & Imaging",
      designation: "Lead Imaging Technologist",
      joiningDate: "2020-04-12",
      salary: 62000,
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
  await db.collection("staffs").insertMany(staffMembers);

  console.log("Creating 16 Expanded Departments...");
  const departmentsData = [
    {
      name: "General Medicine",
      code: "GENMED",
      description: "Comprehensive adult preventive care, chronic illness management, infectious diseases, and diagnostics.",
      headDoctor: "Dr. Rajesh Kumar",
      floor: "Ground Floor, Block A",
      icon: "Stethoscope",
      services: ["Routine OPD", "Diabetes Clinic", "Hypertension Management", "Fever & Infection Care"],
      totalBeds: 35,
      occupiedBeds: 18,
      status: "Active",
      totalDoctors: 8,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Cardiology",
      code: "CARDIO",
      description: "Advanced cardiac care, interventional cardiology, echocardiography, angiography, and coronary care unit.",
      headDoctor: "Dr. Sarah Jenkins",
      floor: "2nd Floor, Wing B",
      icon: "HeartPulse",
      services: ["ECG & 2D Echo", "TMT & Holter Monitoring", "Coronary Angiography", "Pacemaker Clinic"],
      totalBeds: 25,
      occupiedBeds: 16,
      status: "Active",
      totalDoctors: 6,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Neurology & Neurosurgery",
      code: "NEURO",
      description: "State-of-the-art brain & spine disorder management, stroke intervention, epilepsy clinic, and neuro-rehabilitation.",
      headDoctor: "Dr. Vikram Sethi",
      floor: "3rd Floor, Wing A",
      icon: "Brain",
      services: ["Stroke ICU", "EEG & EMG Studies", "Spine Surgery", "Parkinson's Clinic"],
      totalBeds: 20,
      occupiedBeds: 12,
      status: "Active",
      totalDoctors: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Orthopedics & Joint Care",
      code: "ORTHO",
      description: "Joint replacement surgery, sports medicine, fracture clinic, arthroscopy, and robotic joint replacements.",
      headDoctor: "Dr. David Kim",
      floor: "1st Floor, Wing C",
      icon: "Bone",
      services: ["Total Knee/Hip Replacement", "Arthroscopic Surgery", "Sports Injury Clinic", "Fracture Trauma Care"],
      totalBeds: 30,
      occupiedBeds: 22,
      status: "Active",
      totalDoctors: 6,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Pediatrics & Neonatology",
      code: "PEDIA",
      description: "Complete child healthcare, immunization clinic, Level-III NICU/PICU, pediatric surgery, and developmental monitoring.",
      headDoctor: "Dr. Anita Desai",
      floor: "4th Floor, Wing A",
      icon: "Baby",
      services: ["Vaccination Desk", "Level III NICU", "Pediatric Emergency", "Growth & Nutrition Clinic"],
      totalBeds: 24,
      occupiedBeds: 14,
      status: "Active",
      totalDoctors: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Obstetrics & Gynecology",
      code: "OBGYN",
      description: "High-risk pregnancy care, painless normal delivery, modular birthing suites, laparoscopy, and IVF fertility services.",
      headDoctor: "Dr. Priya Sen",
      floor: "4th Floor, Wing B",
      icon: "HeartHandshake",
      services: ["LDR Birthing Suites", "Fetal Medicine", "Laparoscopic Surgeries", "PCOS & Infertility"],
      totalBeds: 28,
      occupiedBeds: 20,
      status: "Active",
      totalDoctors: 7,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Oncology & Cancer Care",
      code: "ONCO",
      description: "Medical, surgical, and radiation oncology, immunotherapy, bone marrow transplant, and specialized daycare chemotherapy.",
      headDoctor: "Dr. Ramanathan Iyer",
      floor: "5th Floor, Tower B",
      icon: "ShieldAlert",
      services: ["Daycare Chemotherapy", "Targeted Therapy", "Tumor Board Reviews", "Palliative Care"],
      totalBeds: 20,
      occupiedBeds: 15,
      status: "Active",
      totalDoctors: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Dermatology & Cosmetology",
      code: "DERMA",
      description: "Clinical dermatology, skin allergy diagnosis, laser treatments, hair restoration, and aesthetic medicine.",
      headDoctor: "Dr. Emily Taylor",
      floor: "1st Floor, OPD Complex",
      icon: "Sparkles",
      services: ["Laser Skin Surgery", "Allergy Patch Testing", "Acne & Scar Treatment", "Hair Loss Clinic"],
      totalBeds: 5,
      occupiedBeds: 1,
      status: "Active",
      totalDoctors: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Ophthalmology (Eye Care)",
      code: "OPHTHA",
      description: "Micro-incision cataract surgery, LASIK laser vision correction, glaucoma management, and pediatric ophthalmology.",
      headDoctor: "Dr. Arvind Shrivastava",
      floor: "Ground Floor, OPD Wing",
      icon: "Eye",
      services: ["Blade-free LASIK", "Phaco Cataract Surgery", "Retina Laser Clinic", "Glaucoma Screening"],
      totalBeds: 10,
      occupiedBeds: 4,
      status: "Active",
      totalDoctors: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "ENT & Head Neck Surgery",
      code: "ENT",
      description: "Endoscopic sinus surgery, microscopic ear surgery, snoring & sleep apnea clinic, and vertigo management.",
      headDoctor: "Dr. Sanjay Bhatt",
      floor: "1st Floor, OPD Complex",
      icon: "Ear",
      services: ["Audiometry & Speech Therapy", "Endoscopic Sinus Surgery", "Vertigo Clinic", "Tympanoplasty"],
      totalBeds: 12,
      occupiedBeds: 5,
      status: "Active",
      totalDoctors: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Emergency & Trauma 24x7",
      code: "EMERG",
      description: "24-hour rapid response emergency triage, polytrauma resuscitation, cardiac emergency, and mobile ACLS ambulances.",
      headDoctor: "Dr. Robert Martinez",
      floor: "Ground Floor, Dedicated Gate 1",
      icon: "Ambulance",
      services: ["Triage Level 1-4", "ACLS Ambulance Support", "Trauma Operation Theater", "Poison & Burn Unit"],
      totalBeds: 25,
      occupiedBeds: 19,
      status: "Active",
      totalDoctors: 10,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Gastroenterology & Hepatology",
      code: "GASTRO",
      description: "Advanced endoscopy, colonoscopy, ERCP, liver disease clinic, and minimally invasive GI surgeries.",
      headDoctor: "Dr. Manoj Verma",
      floor: "2nd Floor, Wing C",
      icon: "Activity",
      services: ["Upper GI Endoscopy", "Colonoscopy & Polypectomy", "Fatty Liver Clinic", "Capsule Endoscopy"],
      totalBeds: 18,
      occupiedBeds: 11,
      status: "Active",
      totalDoctors: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Nephrology & Urology",
      code: "NEPHRO",
      description: "Modern 24-bed hemodialysis center, kidney transplant clinic, laser lithotripsy for kidney stones, and prostate care.",
      headDoctor: "Dr. Suresh Nambiar",
      floor: "3rd Floor, Wing B",
      icon: "Filter",
      services: ["24x7 Dialysis Unit", "Laser Kidney Stone RIRS", "Transplant Follow-up", "Prostate Laser Surgery"],
      totalBeds: 26,
      occupiedBeds: 21,
      status: "Active",
      totalDoctors: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Pulmonology & Chest Medicine",
      code: "PULMO",
      description: "Comprehensive respiratory medicine, asthma & COPD clinic, bronchoscopy suite, and sleep disorder lab.",
      headDoctor: "Dr. K.V. Mohan",
      floor: "2nd Floor, Wing A",
      icon: "Wind",
      services: ["Spirometry & PFT", "Diagnostic Bronchoscopy", "Sleep Apnea Study", "Asthma & Allergy Clinic"],
      totalBeds: 16,
      occupiedBeds: 9,
      status: "Active",
      totalDoctors: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Psychiatry & Behavioral Health",
      code: "PSYCH",
      description: "Clinical psychology, addiction de-addiction therapy, mood disorder clinic, and stress management counseling.",
      headDoctor: "Dr. Ananya Sharma",
      floor: "1st Floor, Quiet Wing",
      icon: "Smile",
      services: ["Psychotherapy & Counseling", "De-addiction Clinic", "Child Behavior Assessment", "Stress & Anxiety Care"],
      totalBeds: 10,
      occupiedBeds: 3,
      status: "Active",
      totalDoctors: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Dental & Maxillofacial",
      code: "DENTAL",
      description: "Cosmetic dentistry, root canal treatments, painless dental implants, orthodontic braces, and facial trauma repair.",
      headDoctor: "Dr. Sneha Pillai",
      floor: "Ground Floor, Dental Suite",
      icon: "SmilePlus",
      services: ["Painless Root Canal", "Titanium Implants", "Invisible Aligners", "Smile Designing"],
      totalBeds: 6,
      occupiedBeds: 2,
      status: "Active",
      totalDoctors: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
  await db.collection("departments").insertMany(departmentsData);

  console.log("Creating Doctors list...");
  const doctorsData = [
    {
      doctorId: "DOC-101",
      name: "Dr. Sarah Jenkins",
      email: "sarah.jenkins@hospital.com",
      phone: "+91 98765-43201",
      department: "Cardiology",
      specialization: "Senior Interventional Cardiologist",
      qualification: "MBBS, MD (Medicine), DM (Cardiology), FESC",
      experienceYears: 14,
      consultationFee: 800,
      emergencyFee: 1500,
      teleconsultationFee: 600,
      roomNumber: "201",
      mciNumber: "MCI-CARD-9921",
      slotDurationMinutes: 15,
      availableDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
      workingHours: { start: "09:00 AM", end: "05:00 PM" },
      status: "Active",
      photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80",
      rating: 4.9,
      totalReviews: 248,
      bio: "Over 14 years of experience in complex coronary angioplasty, transcatheter aortic valve implantation (TAVI), and heart failure management.",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      doctorId: "DOC-102",
      name: "Dr. David Kim",
      email: "david.kim@hospital.com",
      phone: "+91 98765-43202",
      department: "Orthopedics & Joint Care",
      specialization: "Joint Replacement & Robotic Surgeon",
      qualification: "MBBS, MS (Ortho), M.Ch (UK), FIJR",
      experienceYears: 12,
      consultationFee: 700,
      emergencyFee: 1200,
      teleconsultationFee: 500,
      roomNumber: "105",
      mciNumber: "MCI-ORTH-4412",
      slotDurationMinutes: 15,
      availableDays: ["Monday", "Wednesday", "Friday", "Saturday"],
      workingHours: { start: "10:00 AM", end: "06:00 PM" },
      status: "Active",
      photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
      rating: 4.8,
      totalReviews: 184,
      bio: "Pioneer in robotic total knee and hip replacements with minimal recovery times and sports arthroscopic reconstructions.",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      doctorId: "DOC-103",
      name: "Dr. Anita Desai",
      email: "anita.desai@hospital.com",
      phone: "+91 98765-43203",
      department: "Pediatrics & Neonatology",
      specialization: "Senior Pediatrician & Neonatal Intensivist",
      qualification: "MBBS, MD (Pediatrics), Fellowship in Neonatology",
      experienceYears: 10,
      consultationFee: 600,
      emergencyFee: 1000,
      teleconsultationFee: 450,
      roomNumber: "402",
      mciNumber: "MCI-PED-8391",
      slotDurationMinutes: 15,
      availableDays: ["Monday", "Tuesday", "Thursday", "Friday", "Sunday"],
      workingHours: { start: "08:30 AM", end: "04:30 PM" },
      status: "Active",
      photo: "https://images.unsplash.com/photo-1594824813600-d820c8dc7fcf?w=500&auto=format&fit=crop&q=80",
      rating: 4.9,
      totalReviews: 312,
      bio: "Dedicated child healthcare specialist handling newborn intensive care, childhood immunization schedules, and developmental milestones.",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      doctorId: "DOC-104",
      name: "Dr. Vikram Sethi",
      email: "vikram.sethi@hospital.com",
      phone: "+91 98765-43204",
      department: "Neurology & Neurosurgery",
      specialization: "Consultant Neurologist & Stroke Specialist",
      qualification: "MBBS, MD, DM (Neurology)",
      experienceYears: 16,
      consultationFee: 900,
      emergencyFee: 1800,
      teleconsultationFee: 750,
      roomNumber: "304",
      mciNumber: "MCI-NEUR-7721",
      slotDurationMinutes: 20,
      availableDays: ["Tuesday", "Wednesday", "Thursday", "Saturday"],
      workingHours: { start: "10:00 AM", end: "05:00 PM" },
      status: "Active",
      photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
      rating: 4.9,
      totalReviews: 195,
      bio: "Expert in acute stroke thrombolysis, epilepsy, migraines, neuropathies, and Parkinson's disease deep brain stimulation assessment.",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      doctorId: "DOC-105",
      name: "Dr. Priya Sen",
      email: "priya.sen@hospital.com",
      phone: "+91 98765-43205",
      department: "Obstetrics & Gynecology",
      specialization: "Senior Gynaecologist & Laparoscopic Surgeon",
      qualification: "MBBS, MS (OBGYN), DNB, FICOG",
      experienceYears: 15,
      consultationFee: 750,
      emergencyFee: 1400,
      teleconsultationFee: 550,
      roomNumber: "408",
      mciNumber: "MCI-OBGYN-6612",
      slotDurationMinutes: 15,
      availableDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
      workingHours: { start: "09:30 AM", end: "05:30 PM" },
      status: "Active",
      photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80",
      rating: 5.0,
      totalReviews: 420,
      bio: "Specializing in high-risk pregnancies, natural painless childbirth, PCOS management, and advanced gynecological laparoscopy.",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      doctorId: "DOC-106",
      name: "Dr. Robert Martinez",
      email: "robert.martinez@hospital.com",
      phone: "+91 98765-43206",
      department: "Emergency & Trauma 24x7",
      specialization: "Head of Emergency Medicine & Critical Care",
      qualification: "MBBS, MD (Emergency Medicine), MRCEM (UK)",
      experienceYears: 11,
      consultationFee: 650,
      emergencyFee: 1000,
      teleconsultationFee: 500,
      roomNumber: "ER-01",
      mciNumber: "MCI-EMER-1102",
      slotDurationMinutes: 10,
      availableDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
      workingHours: { start: "08:00 AM", end: "08:00 PM" },
      status: "Active",
      photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
      rating: 4.8,
      totalReviews: 160,
      bio: "Certified ACLS/ATLS instructor leading 24x7 rapid resuscitation team, trauma management, and disaster response.",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
  const createdDoctors = await db.collection("doctors").insertMany(doctorsData);
  const doctorIds = Object.values(createdDoctors.insertedIds);

  console.log("Creating Patients with ABHA Details...");
  const patientsData = [
    {
      patientId: "PAT-1001",
      name: "Rajesh Sharma",
      gender: "Male",
      dob: "1980-05-14",
      age: 44,
      phone: "+91 98112-23344",
      email: "rajesh.sharma@gmail.com",
      bloodGroup: "O+",
      address: "B-42, Shivalik Enclave, Malviya Nagar",
      city: "New Delhi",
      emergencyContact: {
        name: "Sunita Sharma",
        relationship: "Spouse",
        phone: "+91 98112-23345",
      },
      allergies: ["Penicillin", "Sulfa Drugs"],
      medicalHistory: ["Hypertension (Diagnosed 2019)", "Type 2 Diabetes"],
      abhaNumber: "91-4421-8890-1234",
      abhaAddress: "rajesh.sharma@abdm",
      status: "Inpatient",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      patientId: "PAT-1002",
      name: "Pooja Verma",
      gender: "Female",
      dob: "1994-08-22",
      age: 30,
      phone: "+91 98223-34455",
      email: "pooja.v@outlook.com",
      bloodGroup: "A+",
      address: "Flat 304, Palm Grove Apartments",
      city: "Gurugram",
      emergencyContact: {
        name: "Amit Verma",
        relationship: "Spouse",
        phone: "+91 98223-34456",
      },
      allergies: ["None"],
      medicalHistory: ["Mild Asthma", "Gestational Checkup (28 Weeks)"],
      abhaNumber: "91-8823-1194-5561",
      abhaAddress: "pooja.verma@abdm",
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      patientId: "PAT-1003",
      name: "Aarav Gupta",
      gender: "Male",
      dob: "2018-02-10",
      age: 6,
      phone: "+91 98334-45566",
      email: "gupta.parents@gmail.com",
      bloodGroup: "B+",
      address: "House 12, Sector 15",
      city: "Noida",
      emergencyContact: {
        name: "Meenakshi Gupta",
        relationship: "Mother",
        phone: "+91 98334-45566",
      },
      allergies: ["Peanuts"],
      medicalHistory: ["Allergic Rhinitis"],
      abhaNumber: "91-3312-7789-9901",
      abhaAddress: "aarav.gupta@abdm",
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      patientId: "PAT-1004",
      name: "Virendra Malhotra",
      gender: "Male",
      dob: "1962-11-03",
      age: 62,
      phone: "+91 98445-56677",
      email: "v.malhotra@yahoo.co.in",
      bloodGroup: "AB+",
      address: "C-108, GK Part 2",
      city: "New Delhi",
      emergencyContact: {
        name: "Rohit Malhotra",
        relationship: "Son",
        phone: "+91 98445-56678",
      },
      allergies: ["Aspirin"],
      medicalHistory: ["Coronary Artery Disease (Post PTCA 2021)", "Osteoarthritis"],
      abhaNumber: "91-1122-3344-5566",
      abhaAddress: "virendra.m@abdm",
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      patientId: "PAT-1005",
      name: "Meera Nair",
      gender: "Female",
      dob: "1988-04-19",
      age: 36,
      phone: "+91 98556-67788",
      email: "meera.nair@gmail.com",
      bloodGroup: "O-",
      address: "D-55, Indirapuram",
      city: "Ghaziabad",
      emergencyContact: {
        name: "Suresh Nair",
        relationship: "Spouse",
        phone: "+91 98556-67789",
      },
      allergies: ["Ciprofloxacin"],
      medicalHistory: ["Migraine", "Hypothyroidism"],
      abhaNumber: "91-7788-9900-1122",
      abhaAddress: "meera.nair@abdm",
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
  const createdPatients = await db.collection("patients").insertMany(patientsData);
  const patientIds = Object.values(createdPatients.insertedIds);

  console.log("Creating ABHA Cards for ABDM Integration...");
  const abhaCardsData = [
    {
      abhaNumber: "91-4421-8890-1234",
      abhaAddress: "rajesh.sharma@abdm",
      fullName: "Rajesh Sharma",
      gender: "Male",
      dob: "1980-05-14",
      mobile: "+91 98112-23344",
      aadhaarLast4: "4421",
      address: "B-42, Shivalik Enclave, Malviya Nagar",
      state: "Delhi",
      district: "South Delhi",
      pincode: "110017",
      patientId: patientIds[0].toString(),
      photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
      qrData: "ABHA:91-4421-8890-1234|PHR:rajesh.sharma@abdm|DOB:14/05/1980|GEN:M",
      verificationStatus: "Verified",
      careContexts: [
        {
          contextType: "OPD Visit",
          referenceId: "OPD-2026-9901",
          title: "Cardiology Routine Evaluation",
          linkedDate: "2026-09-01T10:00:00Z",
        },
        {
          contextType: "Prescription",
          referenceId: "RX-2026-4412",
          title: "Anti-hypertensive & Glycemic Regimen",
          linkedDate: "2026-09-01T10:30:00Z",
        },
        {
          contextType: "Diagnostic Report",
          referenceId: "LAB-2026-8812",
          title: "Comprehensive Lipid & HbA1c Panel",
          linkedDate: "2026-09-02T14:00:00Z",
        },
      ],
      consentRequests: [
        {
          requestId: "REQ-ABDM-88219",
          requesterName: "Apollo Clinics South Delhi",
          purpose: "Second opinion on post-cardiac care",
          grantedFrom: "2026-09-01",
          grantedTo: "2026-10-01",
          status: "Granted",
        },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      abhaNumber: "91-8823-1194-5561",
      abhaAddress: "pooja.verma@abdm",
      fullName: "Pooja Verma",
      gender: "Female",
      dob: "1994-08-22",
      mobile: "+91 98223-34455",
      aadhaarLast4: "1194",
      address: "Flat 304, Palm Grove Apartments",
      state: "Haryana",
      district: "Gurugram",
      pincode: "122001",
      patientId: patientIds[1].toString(),
      photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
      qrData: "ABHA:91-8823-1194-5561|PHR:pooja.verma@abdm|DOB:22/08/1994|GEN:F",
      verificationStatus: "Verified",
      careContexts: [
        {
          contextType: "OPD Visit",
          referenceId: "OPD-2026-1022",
          title: "Antenatal Trimester 3 Screening",
          linkedDate: "2026-09-05T11:00:00Z",
        },
        {
          contextType: "Diagnostic Report",
          referenceId: "RAD-2026-3391",
          title: "Fetal Wellbeing Doppler Ultrasound",
          linkedDate: "2026-09-05T12:30:00Z",
        },
      ],
      consentRequests: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      abhaNumber: "91-1122-3344-5566",
      abhaAddress: "virendra.m@abdm",
      fullName: "Virendra Malhotra",
      gender: "Male",
      dob: "1962-11-03",
      mobile: "+91 98445-56677",
      aadhaarLast4: "3344",
      address: "C-108, GK Part 2",
      state: "Delhi",
      district: "South Delhi",
      pincode: "110048",
      patientId: patientIds[3].toString(),
      photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80",
      qrData: "ABHA:91-1122-3344-5566|PHR:virendra.m@abdm|DOB:03/11/1962|GEN:M",
      verificationStatus: "Verified",
      careContexts: [
        {
          contextType: "OPD Visit",
          referenceId: "OPD-2026-7782",
          title: "Orthopedic Knee Osteoarthritis Review",
          linkedDate: "2026-09-08T09:30:00Z",
        },
      ],
      consentRequests: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
  await db.collection("abhacards").insertMany(abhaCardsData);

  console.log("Creating Health Packages...");
  const healthPackagesData = [
    {
      packageCode: "PKG-PREV-01",
      name: "MediPulse Comprehensive Master Health Checkup",
      category: "Preventive",
      price: 2999,
      originalPrice: 5999,
      description: "Complete 72-parameter diagnostic assessment including CBC, Kidney Profile, Liver Function, Lipid Panel, Blood Sugar, Thyroid Profile, ECG, Chest X-Ray & Physician Consultation.",
      features: [
        "72 Vital Diagnostic Parameters",
        "Free Home Sample Collection or VIP Lounge Testing",
        "Digital Smart Report in 6 Hours with AI Explainer",
        "Doctor Consultation with Sr. Physician Included",
      ],
      includedTests: [
        "Complete Blood Count (CBC - 24 Parameters)",
        "Lipid Profile (Cholesterol, HDL, LDL, Triglycerides)",
        "Liver Function Test (LFT - 11 Parameters)",
        "Kidney Function Test (KFT - Creatinine, Urea, Uric Acid)",
        "Fasting & Postprandial Blood Sugar + HbA1c",
        "Thyroid Profile (T3, T4, TSH)",
        "Resting 12-Lead ECG",
        "Digital Chest X-Ray (PA View)",
      ],
      includedConsultations: ["Senior Internal Medicine Specialist", "Clinical Dietitian"],
      durationDays: 1,
      popular: true,
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      packageCode: "PKG-CARD-02",
      name: "Advanced Healthy Heart & Cardiac Screening",
      category: "Cardiac",
      price: 4499,
      originalPrice: 8500,
      description: "Dedicated cardiovascular screening package designed by top cardiologists to evaluate coronary risks, lipid biomarkers, and cardiac performance.",
      features: [
        "2D Echocardiography & Color Doppler",
        "TMT (Treadmill Stress Test) or Stress Echo",
        "Cardiac Enzymes & High-Sensitivity Troponin / hs-CRP",
        "1-on-1 Consultation with Interventional Cardiologist",
      ],
      includedTests: [
        "12-Lead Electrocardiogram (ECG)",
        "2D Echocardiography with Color Doppler",
        "Treadmill Stress Test (TMT)",
        "Lipid Fractionation Panel",
        "hs-CRP (Cardiac Risk Marker)",
        "Serum Electrolytes (Na+, K+, Cl-)",
        "HbA1c & Fasting Glucose",
      ],
      includedConsultations: ["Senior Cardiologist", "Cardiac Nutrition Specialist"],
      durationDays: 1,
      popular: true,
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      packageCode: "PKG-MAT-03",
      name: "Bliss Motherhood & Maternity Care Package",
      category: "Maternity",
      price: 34999,
      originalPrice: 48000,
      description: "All-inclusive maternity journey covering 9 months of antenatal checkups, high-resolution ultrasounds, prenatal yoga, nutrition, and choice of birthing suite.",
      features: [
        "Unlimited Antenatal Gynaecologist Consultations",
        "All Trimester Fetal Ultrasound Scans (NT, Level II Anomaly)",
        "Painless Normal Delivery / Planned C-Section Options",
        "Newborn Neonatal Package & 1st Dose Immunization",
      ],
      includedTests: [
        "NT Scan & Dual Marker Screen",
        "Level II Target Anomaly Ultrasound",
        "Fetal Doppler & Growth Scans",
        "Routine Antenatal Blood Panels & GTT",
        "Thyroid & Torch Profile",
      ],
      includedConsultations: ["Senior Obstetrician", "Lactation Consultant", "Prenatal Physiotherapist"],
      durationDays: 270,
      popular: true,
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      packageCode: "PKG-SEN-04",
      name: "Senior Citizen Platinum Wellness Package",
      category: "Senior Citizen",
      price: 3999,
      originalPrice: 7500,
      description: "Tailored geriatric health assessment evaluating bone mineral density, joint health, prostate/mammogram screening, cardiovascular health, and memory evaluation.",
      features: [
        "DEXA Bone Mineral Density Scan",
        "Prostate Specific Antigen (PSA) / Pap Smear",
        "Audiometry Hearing Screen & Eye Glaucoma Check",
        "Geriatric Care Plan & Medication Review",
      ],
      includedTests: [
        "Complete Hemogram & ESR",
        "Total Vitamin D3 & Vitamin B12",
        "Serum Calcium & Phosphorus",
        "PSA (for Men) / CA-125 (for Women)",
        "Renal & Hepatic Profiles",
        "Urine Routine & Microscopic",
      ],
      includedConsultations: ["Geriatric Physician", "Orthopedic Specialist", "Ophthalmologist"],
      durationDays: 1,
      popular: false,
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      packageCode: "PKG-DIAB-05",
      name: "Comprehensive Diabetes Reversal & Care Plan",
      category: "Diabetes",
      price: 2499,
      originalPrice: 4800,
      description: "Holistic 360-degree diabetic evaluation to prevent microvascular and macrovascular complications, neuropathy screening, and personalized diet charts.",
      features: [
        "Quarterly HbA1c & Average Blood Sugar Tracker",
        "Diabetic Retinopathy Eye Fundus Examination",
        "Biothesiometry Foot Neuropathy Screening",
        "Continuous Glucose Monitoring (CGM) Doctor Analysis",
      ],
      includedTests: [
        "HbA1c & Fasting / PP Blood Sugar",
        "Urine Microalbumin / Creatinine Ratio (Early Kidney Marker)",
        "Lipid Profile & Serum Creatinine",
        "Fundus Camera Retinal Screen",
      ],
      includedConsultations: ["Endocrinologist / Diabetologist", "Certified Diabetes Educator"],
      durationDays: 90,
      popular: false,
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
  await db.collection("healthpackages").insertMany(healthPackagesData);

  console.log("Creating TPA & Insurance Claims...");
  const insuranceClaimsData = [
    {
      claimId: "CLM-2026-9011",
      patient: patientIds[0],
      tpaCompany: "Star Health & Allied Insurance",
      policyNumber: "POL-STAR-8839210-A",
      policyHolderName: "Rajesh Sharma",
      hospitalizationType: "Cashless",
      claimedAmount: 145000,
      approvedAmount: 138000,
      admissionId: "ADM-2026-001",
      treatmentName: "Coronary Angioplasty with Drug Eluting Stent (DES)",
      status: "Approved",
      queryDetails: "All initial treatment records verified. Pre-auth sanctioned ₹1,38,000.",
      claimDate: "2026-09-03",
      settledDate: "2026-09-04",
      documents: ["Pre-Auth Request Form", "Cardiology Doctor Notes", "Diagnostic Angiogram Report"],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      claimId: "CLM-2026-9012",
      patient: patientIds[3],
      tpaCompany: "HDFC ERGO General Insurance (Medi Assist TPA)",
      policyNumber: "POL-HDFC-5519283-B",
      policyHolderName: "Virendra Malhotra",
      hospitalizationType: "Cashless",
      claimedAmount: 220000,
      approvedAmount: 210000,
      admissionId: "ADM-2026-002",
      treatmentName: "Total Knee Replacement (Right Joint Robotic Arthroplasty)",
      status: "Submitted",
      queryDetails: "Initial cashless guarantee letter issued. Final bills awaiting submission.",
      claimDate: "2026-09-07",
      documents: ["Cashless Authorization Form", "X-Ray Joint Scans", "Implant Barcode Certificate"],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      claimId: "CLM-2026-9013",
      patient: patientIds[1],
      tpaCompany: "ICICI Lombard Health Care",
      policyNumber: "POL-ICICI-9921827-C",
      policyHolderName: "Pooja Verma",
      hospitalizationType: "Cashless",
      claimedAmount: 65000,
      approvedAmount: 65000,
      treatmentName: "Maternity Antenatal High-Risk Monitoring & Elective Care",
      status: "Approved",
      queryDetails: "Cashless eligibility verified under corporate group policy.",
      claimDate: "2026-09-09",
      documents: ["Policy Card", "Doctor Admission Note"],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
  await db.collection("insuranceclaims").insertMany(insuranceClaimsData);

  console.log("Creating Inpatient Admissions & Bed Matrix...");
  const bedsData = [
    {
      bedNumber: "BED-ICU-01",
      ward: "Intensive Care Unit (ICU)",
      roomNumber: "ICU-101",
      type: "ICU",
      dailyRate: 4500,
      status: "Occupied",
      patientName: "Rajesh Sharma",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      bedNumber: "BED-ICU-02",
      ward: "Intensive Care Unit (ICU)",
      roomNumber: "ICU-102",
      type: "ICU",
      dailyRate: 4500,
      status: "Available",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      bedNumber: "BED-ICU-03",
      ward: "Intensive Care Unit (ICU)",
      roomNumber: "ICU-103",
      type: "ICU",
      dailyRate: 4500,
      status: "Available",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      bedNumber: "BED-PVT-201",
      ward: "Deluxe Private Ward",
      roomNumber: "201",
      type: "Deluxe",
      dailyRate: 3200,
      status: "Occupied",
      patientName: "Virendra Malhotra",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      bedNumber: "BED-PVT-202",
      ward: "Deluxe Private Ward",
      roomNumber: "202",
      type: "Deluxe",
      dailyRate: 3200,
      status: "Available",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      bedNumber: "BED-SEMI-301",
      ward: "Semi-Private Ward",
      roomNumber: "301-A",
      type: "Semi-Private",
      dailyRate: 1800,
      status: "Available",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      bedNumber: "BED-SEMI-302",
      ward: "Semi-Private Ward",
      roomNumber: "301-B",
      type: "Semi-Private",
      dailyRate: 1800,
      status: "Available",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      bedNumber: "BED-GEN-401",
      ward: "General Medical Ward",
      roomNumber: "GW-1",
      type: "General",
      dailyRate: 800,
      status: "Available",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      bedNumber: "BED-GEN-402",
      ward: "General Medical Ward",
      roomNumber: "GW-2",
      type: "General",
      dailyRate: 800,
      status: "Available",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      bedNumber: "BED-EMERG-01",
      ward: "Emergency Triage",
      roomNumber: "ER-Bay-1",
      type: "Emergency",
      dailyRate: 1500,
      status: "Occupied",
      patientName: "Emergency Intake #91",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      bedNumber: "BED-EMERG-02",
      ward: "Emergency Triage",
      roomNumber: "ER-Bay-2",
      type: "Emergency",
      dailyRate: 1500,
      status: "Available",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
  const createdBeds = await db.collection("beds").insertMany(bedsData);
  const bedIds = Object.values(createdBeds.insertedIds);

  console.log("Creating Active Inpatient Admissions...");
  const admissionsData = [
    {
      admissionId: "ADM-2026-001",
      patient: patientIds[0],
      doctor: doctorIds[0],
      department: "Cardiology",
      ward: "Intensive Care Unit (ICU)",
      roomNumber: "ICU-101",
      bed: bedIds[0],
      admissionDate: "2026-09-02",
      admissionReason: "Acute Coronary Syndrome, Unstable Angina. Underwent PCI.",
      treatmentPlan: "Post-PCI continuous cardiac telemetry, dual antiplatelet therapy, statins, strict fluid balance.",
      vitalsLog: [
        {
          date: "2026-09-10 08:00 AM",
          bp: "128/82 mmHg",
          pulse: "74 bpm",
          temp: "98.4 F",
          spo2: "99%",
          recordedBy: "Nurse Clara Oswald",
        },
        {
          date: "2026-09-10 02:00 PM",
          bp: "124/80 mmHg",
          pulse: "72 bpm",
          temp: "98.6 F",
          spo2: "98%",
          recordedBy: "Nurse Clara Oswald",
        },
      ],
      status: "Admitted",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      admissionId: "ADM-2026-002",
      patient: patientIds[3],
      doctor: doctorIds[1],
      department: "Orthopedics & Joint Care",
      ward: "Deluxe Private Ward",
      roomNumber: "201",
      bed: bedIds[3],
      admissionDate: "2026-09-06",
      admissionReason: "Severe Grade IV Osteoarthritis Right Knee. Total Knee Arthroplasty performed.",
      treatmentPlan: "Post-op physiotherapy, cryo-cuff therapy, DVT prophylaxis, analgesia.",
      vitalsLog: [
        {
          date: "2026-09-10 09:30 AM",
          bp: "132/84 mmHg",
          pulse: "76 bpm",
          temp: "98.5 F",
          spo2: "99%",
          recordedBy: "Nurse Clara Oswald",
        },
      ],
      status: "Under Treatment",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
  await db.collection("admissions").insertMany(admissionsData);

  console.log("Creating Appointments (including Teleconsultations)...");
  const appointmentsData = [
    {
      appointmentId: "APT-2026-101",
      patient: patientIds[0],
      doctor: doctorIds[0],
      department: "Cardiology",
      appointmentDate: "2026-09-12",
      timeSlot: "09:30 AM - 09:45 AM",
      type: "Follow-up",
      status: "Confirmed",
      reason: "Post-stenting 2-week cardiovascular review and lipid panel check.",
      vitals: {
        bp: "128/82",
        pulse: "74",
        temperature: "98.4",
        spo2: "99%",
        weight: "76 kg",
        height: "175 cm",
      },
      meetingUrl: "https://meet.medipulse.com/room/apt-101-sarah",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      appointmentId: "APT-2026-102",
      patient: patientIds[1],
      doctor: doctorIds[4],
      department: "Obstetrics & Gynecology",
      appointmentDate: "2026-09-12",
      timeSlot: "10:00 AM - 10:15 AM",
      type: "Routine Checkup",
      status: "Scheduled",
      reason: "Trimester 3 antenatal scan review and birthing suite plan.",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      appointmentId: "APT-2026-103",
      patient: patientIds[2],
      doctor: doctorIds[2],
      department: "Pediatrics & Neonatology",
      appointmentDate: "2026-09-12",
      timeSlot: "11:00 AM - 11:15 AM",
      type: "General",
      status: "Scheduled",
      reason: "Seasonal allergy evaluation, persistent dry cough and sneezing.",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      appointmentId: "APT-2026-104",
      patient: patientIds[4],
      doctor: doctorIds[3],
      department: "Neurology & Neurosurgery",
      appointmentDate: "2026-09-13",
      timeSlot: "02:00 PM - 02:20 PM",
      type: "Teleconsultation",
      status: "Confirmed",
      reason: "Chronic migraine with visual aura flare-up. Video consultation requested.",
      meetingUrl: "https://meet.medipulse.com/room/apt-104-tele-neuro",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
  await db.collection("appointments").insertMany(appointmentsData);

  console.log("Creating OPD Queue records...");
  const opdRecords = [
    {
      tokenNumber: 1,
      patient: patientIds[0],
      doctor: doctorIds[0],
      department: "Cardiology",
      date: "2026-09-11",
      vitals: {
        bp: "128/82",
        pulse: "74",
        temperature: "98.4",
        spo2: "99%",
        weight: "76 kg",
        height: "175 cm",
      },
      symptoms: "Mild exertional fatigue, taking prescribed beta-blockers regularly.",
      diagnosis: "Post-PTCA Recovery, Stable Hemodynamics",
      status: "Completed",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      tokenNumber: 2,
      patient: patientIds[1],
      doctor: doctorIds[4],
      department: "Obstetrics & Gynecology",
      date: "2026-09-11",
      vitals: {
        bp: "116/74",
        pulse: "82",
        temperature: "98.6",
        spo2: "99%",
        weight: "64 kg",
        height: "162 cm",
      },
      symptoms: "Normal fetal movements felt, mild lower back ache.",
      diagnosis: "Antenatal 28 Weeks Gestation",
      status: "In Consultation",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      tokenNumber: 3,
      patient: patientIds[2],
      doctor: doctorIds[2],
      department: "Pediatrics & Neonatology",
      date: "2026-09-11",
      vitals: {
        bp: "96/60",
        pulse: "94",
        temperature: "99.1",
        spo2: "98%",
        weight: "21 kg",
        height: "114 cm",
      },
      symptoms: "Dry cough for 3 days, watery eyes, runny nose.",
      status: "Waiting",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
  await db.collection("opdrecords").insertMany(opdRecords);

  console.log("Creating Pharmacy Medicines & Diagnostic Tests...");
  const medicinesData = [
    {
      name: "Atorvastatin 20mg",
      genericName: "Atorvastatin Calcium",
      category: "Tablet",
      manufacturer: "Sun Pharma",
      batchNumber: "BN-2026-AT91",
      stockQuantity: 450,
      minThreshold: 50,
      purchasePrice: 85,
      sellingPrice: 120,
      expiryDate: "2028-06-30",
      locationRack: "Rack A-04",
      status: "In Stock",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Telmisartan 40mg + Amlodipine 5mg",
      genericName: "Telmisartan + Amlodipine",
      category: "Tablet",
      manufacturer: "Cipla Healthcare",
      batchNumber: "BN-2026-TA88",
      stockQuantity: 320,
      minThreshold: 40,
      purchasePrice: 95,
      sellingPrice: 145,
      expiryDate: "2027-11-30",
      locationRack: "Rack A-08",
      status: "In Stock",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Augmentin 625mg (Amoxicillin + Clavulanic)",
      genericName: "Amoxicillin and Potassium Clavulanate",
      category: "Tablet",
      manufacturer: "GSK Pharmaceuticals",
      batchNumber: "BN-2026-AUG41",
      stockQuantity: 18,
      minThreshold: 30,
      purchasePrice: 160,
      sellingPrice: 220,
      expiryDate: "2027-08-31",
      locationRack: "Rack B-01",
      status: "Low Stock",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Metformin 500mg (Sustained Release)",
      genericName: "Metformin Hydrochloride",
      category: "Tablet",
      manufacturer: "Dr. Reddy's Lab",
      batchNumber: "BN-2026-MET12",
      stockQuantity: 600,
      minThreshold: 60,
      purchasePrice: 40,
      sellingPrice: 65,
      expiryDate: "2028-03-31",
      locationRack: "Rack C-02",
      status: "In Stock",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Paracetamol 650mg (Dolo)",
      genericName: "Paracetamol",
      category: "Tablet",
      manufacturer: "Micro Labs",
      batchNumber: "BN-2026-PCM99",
      stockQuantity: 1200,
      minThreshold: 100,
      purchasePrice: 20,
      sellingPrice: 32,
      expiryDate: "2028-12-31",
      locationRack: "Rack D-01",
      status: "In Stock",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
  await db.collection("medicines").insertMany(medicinesData);

  const labTestsData = [
    {
      testCode: "LAB-CBC-01",
      name: "Complete Blood Count with ESR (CBC)",
      category: "Hematology",
      price: 450,
      sampleType: "Whole Blood (EDTA)",
      turnaroundTime: "3 Hours",
      referenceRanges: [
        { parameter: "Hemoglobin", unit: "g/dL", normalMale: "13.5 - 17.5", normalFemale: "12.0 - 15.5" },
        { parameter: "WBC Count", unit: "/cumm", normalMale: "4,000 - 11,000", normalFemale: "4,000 - 11,000" },
        { parameter: "Platelet Count", unit: "lakh/cumm", normalMale: "1.5 - 4.5", normalFemale: "1.5 - 4.5" },
      ],
      description: "Evaluation of red cells, white cells, hemoglobin, and platelets.",
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      testCode: "LAB-LIPID-02",
      name: "Lipid Profile Comprehensive Panel",
      category: "Biochemistry",
      price: 750,
      sampleType: "Serum (Fasting 12 hrs)",
      turnaroundTime: "4 Hours",
      referenceRanges: [
        { parameter: "Total Cholesterol", unit: "mg/dL", normalMale: "< 200", normalFemale: "< 200" },
        { parameter: "Triglycerides", unit: "mg/dL", normalMale: "< 150", normalFemale: "< 150" },
        { parameter: "HDL Cholesterol", unit: "mg/dL", normalMale: "> 40", normalFemale: "> 50" },
        { parameter: "LDL Cholesterol", unit: "mg/dL", normalMale: "< 100", normalFemale: "< 100" },
      ],
      description: "Cardiovascular risk lipid biomarkers evaluation.",
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      testCode: "LAB-HBA1C-03",
      name: "Glycated Hemoglobin (HbA1c)",
      category: "Biochemistry",
      price: 550,
      sampleType: "Whole Blood (EDTA)",
      turnaroundTime: "2 Hours",
      referenceRanges: [
        { parameter: "HbA1c", unit: "%", normalMale: "< 5.7 (Normal), 5.7-6.4 (Prediabetes)", normalFemale: "< 5.7 (Normal)" },
      ],
      description: "Average blood glucose levels over the last 90 days.",
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
  await db.collection("labtests").insertMany(labTestsData);

  console.log("Creating Prescriptions & Invoices with Taxes & Payment details...");
  const prescriptionsData = [
    {
      prescriptionId: "RX-2026-4412",
      patient: patientIds[0],
      doctor: doctorIds[0],
      date: "2026-09-02",
      diagnosis: "Post-PTCA, Hypertension Stage 1, Type 2 DM",
      clinicalNotes: "Patient recovering smoothly post stent placement. Maintain low-sodium diet and daily 30 min brisk walk.",
      medicines: [
        {
          medicineName: "Atorvastatin 20mg",
          dosage: "1 Tablet",
          frequency: "0-0-1 (Night, after food)",
          duration: "90 Days",
          instructions: "Take with water after dinner",
        },
        {
          medicineName: "Telmisartan 40mg + Amlodipine 5mg",
          dosage: "1 Tablet",
          frequency: "1-0-0 (Morning, after breakfast)",
          duration: "90 Days",
          instructions: "Monitor BP weekly",
        },
        {
          medicineName: "Metformin 500mg (SR)",
          dosage: "1 Tablet",
          frequency: "1-0-1 (Twice daily with meals)",
          duration: "90 Days",
          instructions: "Do not crush or chew",
        },
      ],
      labAdvice: ["Lipid Profile after 6 weeks", "HbA1c after 3 months", "Serum Creatinine"],
      followUpDate: "2026-10-15",
      status: "Active",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
  await db.collection("prescriptions").insertMany(prescriptionsData);

  const invoicesData = [
    {
      invoiceNumber: "INV-2026-0081",
      patient: patientIds[0],
      doctor: doctorIds[0],
      items: [
        {
          description: "Senior Cardiologist OPD Consultation Fee",
          category: "Consultation",
          quantity: 1,
          unitPrice: 800,
          total: 800,
        },
        {
          description: "12-Lead Resting Electrocardiogram (ECG)",
          category: "Laboratory",
          quantity: 1,
          unitPrice: 450,
          total: 450,
        },
        {
          description: "Prescription Medicines (Pharmacy 3-Month Pack)",
          category: "Pharmacy",
          quantity: 1,
          unitPrice: 1250,
          total: 1250,
        },
      ],
      subtotal: 2500,
      discount: 250,
      tax: 270, // GST 12%
      totalAmount: 2520,
      paidAmount: 2520,
      balanceAmount: 0,
      paymentStatus: "Paid",
      paymentMethod: "UPI",
      invoiceDate: "2026-09-02",
      dueDate: "2026-09-02",
      notes: "Paid via UPI QR Transaction ID: UPI-99218273618",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      invoiceNumber: "INV-2026-0082",
      patient: patientIds[1],
      doctor: doctorIds[4],
      items: [
        {
          description: "MediPulse Comprehensive Master Health Checkup Package (PKG-PREV-01)",
          category: "Package",
          quantity: 1,
          unitPrice: 2999,
          total: 2999,
        },
      ],
      subtotal: 2999,
      discount: 0,
      tax: 0,
      totalAmount: 2999,
      paidAmount: 2999,
      balanceAmount: 0,
      paymentStatus: "Paid",
      paymentMethod: "Credit Card",
      invoiceDate: "2026-09-05",
      dueDate: "2026-09-05",
      notes: "Master Health Checkup Package Invoiced. Card ending 4491.",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
  await db.collection("invoices").insertMany(invoicesData);

  console.log("Creating System Notifications...");
  const notificationsData = [
    {
      title: "New ABDM Consent Request",
      message: "Apollo Clinics requested health record access for patient Rajesh Sharma (ABHA: 91-4421-8890-1234).",
      type: "info",
      link: "/abha",
      read: false,
      createdAt: new Date().toISOString(),
    },
    {
      title: "Low Stock Alert: Augmentin 625mg",
      message: "Pharmacy inventory reports Augmentin 625mg is down to 18 units (Threshold: 30 units).",
      type: "warning",
      link: "/pharmacy",
      read: false,
      createdAt: new Date().toISOString(),
    },
    {
      title: "TPA Cashless Pre-Auth Approved",
      message: "Star Health approved ₹1,38,000 for Patient Rajesh Sharma (Claim: CLM-2026-9011).",
      type: "success",
      link: "/billing",
      read: true,
      createdAt: new Date().toISOString(),
    },
  ];
  await db.collection("notifications").insertMany(notificationsData);

  console.log("Creating Sample Patient Referrals...");
  const referralsData = [
    {
      referralId: "REF-2026-0101",
      patient: patientIds[0],
      referringDoctor: doctorIds[0],
      destinationHospital: "All India Institute of Medical Sciences (AIIMS)",
      destinationDepartment: "Cardiothoracic & Vascular Surgery (CTVS)",
      destinationSpecialist: "Dr. V. K. Paul, Senior CTVS Consultant",
      diagnosis: "Severe Multi-Vessel Coronary Artery Disease with Critical Left Main Stenosis",
      reasonForReferral: "Advanced coronary artery bypass graft (CABG) surgery and specialized mechanical circulatory support evaluation.",
      clinicalSummary: "Patient admitted with unstable angina. Angiography showed 90% LAD lesion and 85% LCx stenosis with calcified architecture. Ejection fraction 42%. Hemodynamically stable on dual antiplatelet therapy, IV nitrates, and beta blockers. Requires immediate surgical revascularization at higher tertiary center.",
      priority: "Urgent",
      status: "Accepted",
      referralDate: new Date("2026-09-08"),
      notes: "Bed booked in CTVS ICU at AIIMS. Transfer via Advanced Cardiac Life Support (ACLS) ambulance.",
      transportRequired: true,
      accompanyingNurse: "Nurse Clara Oswald",
      createdBy: "Dr. Alexander Wright",
      createdAt: new Date("2026-09-08"),
      updatedAt: new Date("2026-09-09"),
    },
    {
      referralId: "REF-2026-0102",
      patient: patientIds[2],
      referringDoctor: doctorIds[1],
      destinationHospital: "Tata Memorial Hospital & Advanced Cancer Care Institute",
      destinationDepartment: "Medical Oncology & Hematology",
      destinationSpecialist: "Dr. Priya Sengupta, Lead Hematologist",
      diagnosis: "Suspected Hematological Malignancy / Aplastic Anemia workup",
      reasonForReferral: "Bone marrow biopsy review, cytogenetic analysis, and specialized targeted immunotherapy protocol.",
      clinicalSummary: "Patient presented with severe progressive fatigue, recurrent petechiae, and pancytopenia (Hb: 7.2 g/dL, Platelets: 28,000/mcL, TLC: 2,100/mcL). Peripheral smear indicates dysplastic granulocytes with occasional blast cells. Requires immediate tertiary hematology oncology workup.",
      priority: "Emergency",
      status: "Sent",
      referralDate: new Date("2026-09-10"),
      notes: "Direct line established with Tata Memorial triage coordinator. Transfusion with 2 units PRBC performed before referral.",
      transportRequired: true,
      accompanyingNurse: "Nurse Clara Oswald",
      createdBy: "Dr. Sarah Jenkins",
      createdAt: new Date("2026-09-10"),
      updatedAt: new Date("2026-09-10"),
    },
    {
      referralId: "REF-2026-0103",
      patient: patientIds[1],
      referringDoctor: doctorIds[2],
      destinationHospital: "Apollo Specialty Hospital & Institute of Neurosciences",
      destinationDepartment: "Neurosurgery & Spine Center",
      destinationSpecialist: "Dr. Arvind Chawla",
      diagnosis: "L4-L5 Lumbar Canal Stenosis with Cauda Equina Compression Signs",
      reasonForReferral: "Micro-endoscopic decompression spine surgery and robotic neuro-navigation intervention.",
      clinicalSummary: "Patient suffering from severe radiating lower back pain (radiculopathy) unresponsive to conservative physiotherapy and nerve blocks. MRI demonstrates severe foraminal stenosis with thecal sac deformation.",
      priority: "Normal",
      status: "Pending",
      referralDate: new Date("2026-09-11"),
      notes: "Outpatient referral consultation booked for next Monday.",
      transportRequired: false,
      createdBy: "Dr. Emily Chen",
      createdAt: new Date("2026-09-11"),
      updatedAt: new Date("2026-09-11"),
    },
  ];
  await db.collection("referrals").insertMany(referralsData);

  console.log("Database Seed completed successfully! All collections created and populated.");
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
